### ISSUE TITLE
Doesn't work anymore ;_;

### ISSUE THREAD

**Issue by manolT** [mewforest/google-art-downloader#3]
It seems Google have covered that exploit a well.

**Comment by lovasoa** [comment]
I participated in several other projects that can download images from the current version of google arts & culture. You can use any of them as a replacement:

 - dezoomify : https://github.com/lovasoa/dezoomify
 - dezoomify-rs: https://github.com/lovasoa/dezoomify-rs
 - gapdecoder: https://github.com/gap-decoder/gapdecoder

**Comment by mewforest** [comment]
> It seems Google have covered that exploit a well.

You are not right here. Most of images from Google Arts and Culture with Google-Art-Downloader can be downloaded correctly.
Most of the problems appeared because of non-stable chromedriver support in selenium.

Please describe me your problem in details, if the issue still actual for you:

1. **What the version do you have of Google Chrome?** Chromedriver needs Google Chrome installed.
2. **Which version of the GAD are you running (compiled or source code)**?
3. **What the OS are you using?** Sometimes Chromedriver doesn't working properly on Windows 7 and older.
4. **On which step program stops?**

**Comment by mewforest** [comment]
I've included all needed chromedrivers in last build, so it should fix your problem with continuously starting webdriver.

I've closed this issue for a now. If you stuck with that error on a new release, please create a new issue with template: "Bug report".
